version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: benikvandaagjarig:local
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
