name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type-check
        run: npm run type-check

      - name: Run unit tests (Vitest)
        run: npx vitest run

      - name: Build
        run: npm run build

      - name: Install Playwright browsers and deps
        run: npx playwright install --with-deps

      - name: Run Playwright visual regression (Chromium)
        run: npx playwright test tests/e2e/visual.spec.ts --project=chromium --reporter=list || true

      - name: Run Playwright E2E (Chromium)
        run: npx playwright test --project=chromium --reporter=list

      - name: Collect Playwright report & visual artifacts
        if: always()
        run: |
          mkdir -p test-results/playwright-report || true
          if [ -d playwright-report ]; then cp -r playwright-report test-results/playwright-report; fi
          if [ -d test-results ]; then mkdir -p test-results/visual || true; fi
          # copy any visual diffs or snapshot reports if Playwright produced them
          if [ -d test-results/playwright ]; then cp -r test-results/playwright test-results/visual || true; fi
          if [ -d tests/e2e/__snapshots__ ]; then cp -r tests/e2e/__snapshots__ test-results/visual/snapshots || true; fi

      - name: Upload visual artifacts
        uses: actions/upload-artifact@v4
        with:
          name: visual-artifacts
          path: |
            test-results/playwright-report
            test-results/visual
            tests/e2e/__snapshots__

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
